"""Convert the telemetry file generated by CATS and convert its columns in
order to be compatible with the refined data format."""

import os
import pandas as pd


def main(folder):
    """Read the telemetry file generated by CATS and convert its columns in
    order to be compatible with the refined data format.

    Parameters
    ----------
    folder : str
        Path to the .csv file to be converted.
    """
    # read the .csv file
    df = pd.read_csv(folder)

    df["ts"] = df["ts[deciseconds]"] / 10
    df.drop(columns=["ts[deciseconds]"], inplace=True)

    df["latitude"] = df["lat[deg/10000]"] / 10000
    df.drop(columns=["lat[deg/10000]"], inplace=True)

    df["longitude"] = df["lon[deg/10000]"] / 10000
    df.drop(columns=["lon[deg/10000]"], inplace=True)

    df.sort_values(by=["ts"], inplace=True)

    min_time = df["ts"].iloc[0]
    df["ts"] = df["ts"] - min_time
    df["ts"] = df["ts"].round(1)

    df.drop_duplicates(subset=["ts"], inplace=True)
    df.dropna(how="all", inplace=True)

    df = df[
        [
            "ts",
            "altitude[m]",
            "velocity[m/s]",
            "latitude",
            "longitude",
            # "link", # TODO: what is this?
            # "state", # TODO: what is this?
            # "errors", # TODO: what is this?
            # "battery[decivolts]",
            # "pyro1",
            # "pyro2",
        ]
    ]

    df.to_csv(
        os.path.join(
            os.path.dirname(folder), "refined", "telemetry_" + os.path.basename(folder)
        ),
        index=False,
    )


if __name__ == "__main__":
    list_of_files = [
        "01_astg/GS_log_main_1_1.csv",
        "01_astg/GS_log_main_1.csv",
        "03_air_esiea/gs_log_main_1.csv",
        "03_air_esiea/gs_log_main_2.csv",
        "05_asat/gs_log_main_1.csv",
        "05_asat/gs_log_payload.csv",
        "07_aesir/gs_log_main_1.csv",
        "07_aesir/gs_log_main_2.csv",
        "10_epfl/gs_log_main_1.csv",
        "11_faraday/gs_log_main_1.csv",
        "12_bristol/gs_log_main_1_1.csv",
        "12_bristol/gs_log_payload.csv",
        "16_ns/gs_log_main_1.csv",
        "17_polito/gs_log_main_1_1.csv",
        "17_polito/gs_log_main_1.csv",
        "18_ntnu/gs_log_main_1_1.csv",
        "18_ntnu/gs_log_main_1.csv",
        "19_put/gs_log_main_1_1.csv",
        "19_put/gs_log_main_1.csv",
        "20_red/gs_log_main_1.csv",
        "23_star/gs_log_main_1.csv",
        "23_star/gs_log_payload_1.csv",
    ]
    for f in list_of_files:
        print("\033[91m" + f"Processing '{f}'" + "\033[0m")
        main(f)
    print("\033[91m" + "Done!" + "\033[0m")
